CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "portfolio_settings" (
	"user_id" integer PRIMARY KEY NOT NULL,
	"emergency_fund_eur" numeric(24, 8) DEFAULT '0' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "portfolio_settings" ADD CONSTRAINT "portfolio_settings_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
INSERT INTO "users" DEFAULT VALUES;
--> statement-breakpoint
INSERT INTO "portfolio_settings" ("user_id", "emergency_fund_eur") VALUES (currval('users_id_seq'), 0);
