CREATE TABLE "portfolios" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portfolios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "portfolios" ADD CONSTRAINT "portfolios_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "portfolios_user_name_uidx" ON "portfolios" USING btree ("user_id","name");--> statement-breakpoint
CREATE TRIGGER portfolios_set_updated_at
  BEFORE UPDATE ON public.portfolios
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();--> statement-breakpoint
INSERT INTO "portfolios" ("user_id", "name") VALUES (1, 'Sijoitukset');--> statement-breakpoint
ALTER TABLE "transactions" ADD COLUMN "portfolio_id" integer;--> statement-breakpoint
UPDATE "transactions" SET "portfolio_id" = (SELECT "id" FROM "portfolios" WHERE "user_id" = 1 AND "name" = 'Sijoitukset' LIMIT 1);--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "portfolio_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_portfolio_id_portfolios_id_fk" FOREIGN KEY ("portfolio_id") REFERENCES "public"."portfolios"("id") ON DELETE restrict ON UPDATE no action;
