CREATE TABLE "instrument_composite_constituents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"parent_instrument_id" integer NOT NULL,
	"sort_order" integer NOT NULL,
	"raw_label" text,
	"weight" numeric(24, 8) NOT NULL,
	"target_instrument_id" integer,
	"pseudo_key" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "instrument_composite_constituents_parent_target_ck" CHECK (
		(
			("target_instrument_id" IS NOT NULL)::integer
			+ ("pseudo_key" IS NOT NULL)::integer
		) = 1
	),
	CONSTRAINT "instrument_composite_constituents_pseudo_key_ck" CHECK (
		"pseudo_key" IS NULL
		OR "pseudo_key" IN (
			'other_equities',
			'other_long_bonds',
			'other_short_bonds',
			'cash'
		)
	)
);
--> statement-breakpoint
ALTER TABLE "instrument_composite_constituents" ADD CONSTRAINT "instrument_composite_constituents_parent_instrument_id_instruments_id_fk" FOREIGN KEY ("parent_instrument_id") REFERENCES "public"."instruments"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "instrument_composite_constituents" ADD CONSTRAINT "instrument_composite_constituents_target_instrument_id_instruments_id_fk" FOREIGN KEY ("target_instrument_id") REFERENCES "public"."instruments"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "instrument_composite_constituents_parent_instrument_id_idx" ON "instrument_composite_constituents" USING btree ("parent_instrument_id");
--> statement-breakpoint
CREATE INDEX "instrument_composite_constituents_target_instrument_id_idx" ON "instrument_composite_constituents" USING btree ("target_instrument_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "instrument_composite_constituents_parent_sort_uidx" ON "instrument_composite_constituents" USING btree ("parent_instrument_id","sort_order");
--> statement-breakpoint
CREATE TRIGGER instrument_composite_constituents_set_updated_at
BEFORE UPDATE ON "instrument_composite_constituents"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();
