CREATE TABLE "holding_custom_buckets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "holding_custom_buckets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "holding_custom_buckets_name_trim_ck" CHECK (length(trim("holding_custom_buckets"."name")) > 0)
);
--> statement-breakpoint
CREATE TABLE "portfolio_holding_bucket_assignments" (
	"portfolio_id" integer NOT NULL,
	"instrument_id" integer NOT NULL,
	"bucket_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "portfolio_holding_bucket_assignments_portfolio_id_instrument_id_pk" PRIMARY KEY("portfolio_id","instrument_id")
);
--> statement-breakpoint
ALTER TABLE "holding_custom_buckets" ADD CONSTRAINT "holding_custom_buckets_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portfolio_holding_bucket_assignments" ADD CONSTRAINT "portfolio_holding_bucket_assignments_portfolio_id_portfolios_id_fk" FOREIGN KEY ("portfolio_id") REFERENCES "public"."portfolios"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portfolio_holding_bucket_assignments" ADD CONSTRAINT "portfolio_holding_bucket_assignments_instrument_id_instruments_id_fk" FOREIGN KEY ("instrument_id") REFERENCES "public"."instruments"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portfolio_holding_bucket_assignments" ADD CONSTRAINT "portfolio_holding_bucket_assignments_bucket_id_holding_custom_buckets_id_fk" FOREIGN KEY ("bucket_id") REFERENCES "public"."holding_custom_buckets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "holding_custom_buckets_user_name_uidx" ON "holding_custom_buckets" USING btree ("user_id","name");--> statement-breakpoint
CREATE INDEX "portfolio_holding_bucket_assignments_bucket_id_idx" ON "portfolio_holding_bucket_assignments" USING btree ("bucket_id");