services:
  postgres:
    image: postgres:18-alpine
    ports:
      - "50500:5432"
    environment:
      POSTGRES_USER: investments
      POSTGRES_PASSWORD: investments
      POSTGRES_DB: investments
    volumes:
      - ./.data/postgres:/var/lib/postgresql
