/**
 * Resolve Yahoo English country strings and Seligson Finnish labels to ISO 3166-1 alpha-2.
 * Unknown labels return null → `unknown` geo bucket in `geoBuckets.ts` (not EM).
 *
 * Seligson Maajakauma labels from sample FIDs 800, 5555, 818423, 581, 795, 3333, 88476 are
 * covered; add new `LABEL_TO_ISO` entries when FundViewer introduces new spellings.
 */

/** Same normalization as {@link resolveRegionKeyToIso} for label lookups. */
export function normLabel(s: string): string {
  return s.trim().toLowerCase().replace(/_/g, " ").replace(/\s+/g, " ");
}

/** Lowercase English / Finnish / variant spellings → ISO alpha-2 */
const LABEL_TO_ISO: Record<string, string> = Object.fromEntries(
  [
    // ISO-like / short
    ["uk", "GB"],
    ["u k", "GB"],
    ["usa", "US"],
    ["u s", "US"],
    ["u.s.", "US"],
    ["u.s.a.", "US"],
    ["uae", "AE"],
    ["hong kong sar", "HK"],
    ["macau sar", "MO"],
    // English (Yahoo-style)
    ["united states", "US"],
    ["united states of america", "US"],
    ["united kingdom", "GB"],
    ["great britain", "GB"],
    ["russia", "RU"],
    ["russian federation", "RU"],
    ["south korea", "KR"],
    ["north korea", "KP"],
    ["korea", "KR"],
    ["korea (south)", "KR"],
    ["korea (north)", "KP"],
    ["republic of korea", "KR"],
    ["czech republic", "CZ"],
    ["czechia", "CZ"],
    ["ivory coast", "CI"],
    ["côte d'ivoire", "CI"],
    ["cote d ivoire", "CI"],
    ["vietnam", "VN"],
    ["turkey", "TR"],
    ["türkiye", "TR"],
    ["taiwan", "TW"],
    ["hong kong", "HK"],
    ["macau", "MO"],
    ["macao", "MO"],
    ["swaziland", "SZ"],
    ["eswatini", "SZ"],
    ["burma", "MM"],
    ["east timor", "TL"],
    ["timor-leste", "TL"],
    ["palestine", "PS"],
    ["bolivia", "BO"],
    ["venezuela", "VE"],
    ["brunei", "BN"],
    ["cape verde", "CV"],
    ["cabo verde", "CV"],
    ["democratic republic of the congo", "CD"],
    ["republic of the congo", "CG"],
    ["the bahamas", "BS"],
    ["bahamas", "BS"],
    ["syria", "SY"],
    ["iran", "IR"],
    ["laos", "LA"],
    ["moldova", "MD"],
    ["micronesia", "FM"],
    ["saint kitts and nevis", "KN"],
    ["saint lucia", "LC"],
    ["saint vincent and the grenadines", "VC"],
    ["são tomé and príncipe", "ST"],
    ["sao tome and principe", "ST"],
    // Finnish (Seligson FundViewer maittain)
    ["suomi", "FI"],
    ["ranska", "FR"],
    ["saksa", "DE"],
    ["sveitsi", "CH"],
    ["iso-britannia", "GB"],
    ["alankomaat", "NL"],
    ["espanja", "ES"],
    ["italia", "IT"],
    ["ruotsi", "SE"],
    ["tanska", "DK"],
    ["belgia", "BE"],
    ["yhdysvallat", "US"],
    ["irlanti", "IE"],
    ["luxemburg", "LU"],
    ["portugali", "PT"],
    ["norja", "NO"],
    ["itävalta", "AT"],
    ["kreikka", "GR"],
    ["puola", "PL"],
    ["unkari", "HU"],
    ["romania", "RO"],
    ["bulgaria", "BG"],
    ["kroatia", "HR"],
    ["slovakia", "SK"],
    ["slovenia", "SI"],
    ["viro", "EE"],
    ["latvia", "LV"],
    ["liettua", "LT"],
    ["kypros", "CY"],
    ["malta", "MT"],
    ["islandia", "IS"],
    ["ukraina", "UA"],
    ["serbia", "RS"],
    ["bosnia ja hertzegovina", "BA"],
    ["bosnia", "BA"],
    ["montenegro", "ME"],
    ["pohjois-makedonia", "MK"],
    ["albania", "AL"],
    ["kosovo", "XK"],
    ["valkovenäjä", "BY"],
    ["valkovenaja", "BY"],
    ["moldova", "MD"],
    ["georgia", "GE"],
    ["armenia", "AM"],
    ["azerbaidzan", "AZ"],
    ["azerbaidžan", "AZ"],
    ["kazakstan", "KZ"],
    ["uzbekistan", "UZ"],
    ["turkki", "TR"],
    ["venäjä", "RU"],
    ["venaja", "RU"],
    ["japani", "JP"],
    ["kiina", "CN"],
    ["hongkong", "HK"],
    ["intia", "IN"],
    ["indonesia", "ID"],
    ["thaimaa", "TH"],
    ["vietnam", "VN"],
    ["malesia", "MY"],
    ["filippiinit", "PH"],
    ["singapore", "SG"],
    ["australia", "AU"],
    ["uusi-seelanti", "NZ"],
    ["uusi seelanti", "NZ"],
    ["etelä-korea", "KR"],
    ["etela-korea", "KR"],
    // Seligson FundViewer (e.g. Aasia Indeksirahasto)
    ["korean tasavalta (etelä-korea)", "KR"],
    ["korean tasavalta (etela-korea)", "KR"],
    ["korean tasavalta", "KR"],
    ["taiwan", "TW"],
    ["pakistan", "PK"],
    ["bangladesh", "BD"],
    ["sri lanka", "LK"],
    ["israel", "IL"],
    ["saudi-arabia", "SA"],
    ["saudi arabia", "SA"],
    ["yhdistyneet arabiemiirikunnat", "AE"],
    ["arabiemiirikunnat", "AE"],
    ["qatar", "QA"],
    ["kuwait", "KW"],
    ["bahrain", "BH"],
    ["oman", "OM"],
    ["jordania", "JO"],
    ["libanon", "LB"],
    ["irak", "IQ"],
    ["iran", "IR"],
    ["meksiko", "MX"],
    ["kanada", "CA"],
    ["brasilia", "BR"],
    ["argentiina", "AR"],
    ["chile", "CL"],
    ["kolumbia", "CO"],
    ["peru", "PE"],
    ["etelä-afrikka", "ZA"],
    ["etela-afrikka", "ZA"],
    ["egypti", "EG"],
    ["nigeria", "NG"],
    ["kenia", "KE"],
    ["marokko", "MA"],
    ["tunisia", "TN"],
    ["ghana", "GH"],
    ["islanti", "IS"],
    ["liechtenstein", "LI"],
    ["monaco", "MC"],
    ["andorra", "AD"],
    ["san marino", "SM"],
    ["vatican", "VA"],
    ["gibraltar", "GI"],
    ["jersey", "JE"],
    ["guernsey", "GG"],
    ["mans", "IM"],
    ["faroe islands", "FO"],
    ["färsaaret", "FO"],
    ["greenland", "GL"],
    ["grönlanti", "GL"],
    ["gronlanti", "GL"],
    ["palestiina", "PS"],
    ["mongolia", "MN"],
    ["nepal", "NP"],
    ["bhutan", "BT"],
    ["myanmar", "MM"],
    ["kambodza", "KH"],
    ["kambodža", "KH"],
    ["laos", "LA"],
    ["papua-uusi-ginea", "PG"],
    ["fiji", "FJ"],
  ].map((row): [string, string] => {
    const [k, v] = row as [string, string];
    return [normLabel(k), v];
  }),
);

/** English country name → ISO (Yahoo `countryWeightings` keys are usually full English names). */
const ENGLISH_COUNTRY_TO_ISO: Record<string, string> = Object.fromEntries(
  [
    ["Afghanistan", "AF"],
    ["Albania", "AL"],
    ["Algeria", "DZ"],
    ["Andorra", "AD"],
    ["Angola", "AO"],
    ["Argentina", "AR"],
    ["Armenia", "AM"],
    ["Australia", "AU"],
    ["Austria", "AT"],
    ["Azerbaijan", "AZ"],
    ["Bahamas", "BS"],
    ["Bahrain", "BH"],
    ["Bangladesh", "BD"],
    ["Barbados", "BB"],
    ["Belarus", "BY"],
    ["Belgium", "BE"],
    ["Belize", "BZ"],
    ["Benin", "BJ"],
    ["Bermuda", "BM"],
    ["Bhutan", "BT"],
    ["Bolivia", "BO"],
    ["Bosnia and Herzegovina", "BA"],
    ["Botswana", "BW"],
    ["Brazil", "BR"],
    ["Brunei", "BN"],
    ["Bulgaria", "BG"],
    ["Burkina Faso", "BF"],
    ["Burundi", "BI"],
    ["Cambodia", "KH"],
    ["Cameroon", "CM"],
    ["Canada", "CA"],
    ["Cayman Islands", "KY"],
    ["Chile", "CL"],
    ["China", "CN"],
    ["Colombia", "CO"],
    ["Costa Rica", "CR"],
    ["Croatia", "HR"],
    ["Cyprus", "CY"],
    ["Czech Republic", "CZ"],
    ["Denmark", "DK"],
    ["Dominican Republic", "DO"],
    ["Ecuador", "EC"],
    ["Egypt", "EG"],
    ["Estonia", "EE"],
    ["Ethiopia", "ET"],
    ["Finland", "FI"],
    ["France", "FR"],
    ["Gabon", "GA"],
    ["Georgia", "GE"],
    ["Germany", "DE"],
    ["Ghana", "GH"],
    ["Gibraltar", "GI"],
    ["Greece", "GR"],
    ["Greenland", "GL"],
    ["Guam", "GU"],
    ["Guatemala", "GT"],
    ["Guernsey", "GG"],
    ["Honduras", "HN"],
    ["Hong Kong", "HK"],
    ["Hungary", "HU"],
    ["Iceland", "IS"],
    ["India", "IN"],
    ["Indonesia", "ID"],
    ["Iran", "IR"],
    ["Iraq", "IQ"],
    ["Ireland", "IE"],
    ["Isle of Man", "IM"],
    ["Israel", "IL"],
    ["Italy", "IT"],
    ["Ivory Coast", "CI"],
    ["Jamaica", "JM"],
    ["Japan", "JP"],
    ["Jersey", "JE"],
    ["Jordan", "JO"],
    ["Kazakhstan", "KZ"],
    ["Kenya", "KE"],
    ["Kuwait", "KW"],
    ["Latvia", "LV"],
    ["Lebanon", "LB"],
    ["Liechtenstein", "LI"],
    ["Lithuania", "LT"],
    ["Luxembourg", "LU"],
    ["Macau", "MO"],
    ["Malaysia", "MY"],
    ["Maldives", "MV"],
    ["Malta", "MT"],
    ["Mauritius", "MU"],
    ["Mexico", "MX"],
    ["Moldova", "MD"],
    ["Monaco", "MC"],
    ["Mongolia", "MN"],
    ["Montenegro", "ME"],
    ["Morocco", "MA"],
    ["Mozambique", "MZ"],
    ["Myanmar", "MM"],
    ["Namibia", "NA"],
    ["Nepal", "NP"],
    ["Netherlands", "NL"],
    ["New Zealand", "NZ"],
    ["Nigeria", "NG"],
    ["North Macedonia", "MK"],
    ["Norway", "NO"],
    ["Oman", "OM"],
    ["Pakistan", "PK"],
    ["Panama", "PA"],
    ["Papua New Guinea", "PG"],
    ["Paraguay", "PY"],
    ["Peru", "PE"],
    ["Philippines", "PH"],
    ["Poland", "PL"],
    ["Portugal", "PT"],
    ["Puerto Rico", "PR"],
    ["Qatar", "QA"],
    ["Romania", "RO"],
    ["Russia", "RU"],
    ["Rwanda", "RW"],
    ["San Marino", "SM"],
    ["Saudi Arabia", "SA"],
    ["Senegal", "SN"],
    ["Serbia", "RS"],
    ["Singapore", "SG"],
    ["Slovakia", "SK"],
    ["Slovenia", "SI"],
    ["South Africa", "ZA"],
    ["South Korea", "KR"],
    ["Spain", "ES"],
    ["Sri Lanka", "LK"],
    ["Sweden", "SE"],
    ["Switzerland", "CH"],
    ["Taiwan", "TW"],
    ["Thailand", "TH"],
    ["Tunisia", "TN"],
    ["Turkey", "TR"],
    ["Ukraine", "UA"],
    ["United Arab Emirates", "AE"],
    ["United Kingdom", "GB"],
    ["United States", "US"],
    ["Uruguay", "UY"],
    ["Uzbekistan", "UZ"],
    ["Venezuela", "VE"],
    ["Vietnam", "VN"],
    ["Zambia", "ZM"],
    ["Zimbabwe", "ZW"],
  ].map((row): [string, string] => {
    const [k, v] = row as [string, string];
    return [normLabel(k), v];
  }),
);

for (const [k, v] of Object.entries(ENGLISH_COUNTRY_TO_ISO)) {
  if (!(k in LABEL_TO_ISO)) {
    LABEL_TO_ISO[k] = v;
  }
}

/** Region-like codes that are not ISO 3166-1 alpha-2 countries */
const NOT_STANDALONE_ISO = new Set(["EU", "UN", "QZ"]);

export function resolveRegionKeyToIso(rawKey: string): string | null {
  const t = rawKey.trim();
  if (/^[A-Za-z]{2}$/.test(t)) {
    const u = t.toUpperCase();
    if (NOT_STANDALONE_ISO.has(u)) {
      return null;
    }
    return u;
  }
  const n = normLabel(t);
  return LABEL_TO_ISO[n] ?? null;
}

/**
 * Merge raw region weights into ISO-keyed weights (same key may appear under different labels).
 */
export function normalizeRegionsToIsoKeys(
  regions: Record<string, number>,
): Record<string, number> {
  const out: Record<string, number> = {};
  for (const [rawKey, w] of Object.entries(regions)) {
    if (typeof w !== "number" || !Number.isFinite(w) || w <= 0) {
      continue;
    }
    const iso = resolveRegionKeyToIso(rawKey.trim());
    if (!iso) {
      continue;
    }
    out[iso] = (out[iso] ?? 0) + w;
  }
  return out;
}
